### PR TITLE
Vehicle mod plugin

### PR DESCRIPTION
**Pull request by DarthMan**
The vehicle mod plugin originally coded by SYC, now using the FM api, recoded by DarthMan with improvements.

### CODE REVIEW

**Comment by MrCoala** [comment]
@CodiumAI-Agent /review

**Comment by MrCoala** [comment]
I refactored it a bit, can you update your file and check my changes?

`#pragma compress 1

#include "feckinmad/fm_global"
#include "feckinmad/fm_mapfunc"
#include <fakemeta>
#include <xs>

new g_szPluginAuthor[] = "syc & DarthMan";      // Plugin author name
new const g_szFileName[] = "drivemaps.ini";     // Drive maps file name
new g_iMsgTrain;                                // Train message ID
const InvalidMessage = 0;                       // Invalid message constant
const g_iLinMacDiff = 5;                        // Line macro difference constant
const g_iFlyablePlane = (1 << 0);               // Flyable plane flag
const g_iAllowRollFlag = (1 << 1);              // Allow roll flag
const Float: g_fMaxDistance = 4096.0;           // Maximum distance constant
const Float: g_fSphereDistance = 30.0;          // Sphere distance constant
const Float: g_fTouchDistance = 128.0;          // Touch distance constant
const Float: g_fAngleMultiplier = 2.75;         // Angle multiplier constant
const Float: g_fAngleDiff = 3.5;                // Angle difference constant
const Float: g_fNullAngle = 0.0;                // Null angle constant
new const Float: g_fVecAngleDeg[] = {180.0, 360.0};             // Vector angle degrees
new g_iPlayerTrainFlags[MAX_PLAYERS + 1] = {FM_NULLENT, ...};   // Player train flags
new g_iPlayerTrainEnt[MAX_PLAYERS + 1] = {FM_NULLENT, ...};     // Player train entities
new g_iPlayerPlane[MAX_PLAYERS + 1] = {FM_NULLENT, ...};        // Player planes
new Float: g_fPlayerOldAngle[MAX_PLAYERS + 1];                  // Player old angles

#define PFLAG_ONTRAIN		( 1<<1 ) // On train flag

public plugin_init()
{
    fm_RegisterPlugin(g_szPluginAuthor);
    
    if(!Read_DriveFile())
    {
        pause("d");
        return;
    }

    g_iMsgTrain = get_user_msgid("Train");
    
    register_message(g_iMsgTrain, "Handle_TrainMsg");
    register_forward(FM_StartFrame, "Handle_TrailTimer", true);
}

// Function: Read_DriveFile
// Reads the drive file and checks if the current map is valid.
//
// Returns:
//     True if the current map is found in the drive file, false otherwise.

bool: Read_DriveFile()
{
    new szFile[128];
    fm_BuildAMXFilePath(g_szFileName, szFile, charsmax(szFile), "amxx_configsdir");
    
    new hFile = fopen(szFile, "rt");
    
    if(!hFile)
    {
        fm_WarningLog(FM_FOPEN_WARNING, szFile);
        return false;
    }
    else
    {
        new szCurrentMap[32], szFileBuffer[32];
        get_mapname(szCurrentMap, charsmax(szCurrentMap));
        
        while(!feof(hFile) && fgets(hFile, szFileBuffer, charsmax(szFileBuffer)))
        {
            trim(szFileBuffer);
            
            if(fm_Comment(szFileBuffer))
                continue;
            
            if(!fm_IsMapValid(szFileBuffer))
                continue;
            
            if(equali(szCurrentMap, szFileBuffer))
            {
                fclose(hFile);
                return true;
            }
        }
        
        fclose(hFile);
    }
    
    return false;
}

// Function: Handle_TrailTimer
// Handles the trail timer event.
//
// Note:
//     This function is called periodically to update the train entities for players who are still touching the train.
//     It retrieves the list of players and checks if their train entities and plane entities are valid.
//     If valid, it calls the Update_Train function to update the train entity for each player.

Handle_TrailTimer()
{
    static Float: fTickAt, Float: fGameTime;
    fGameTime = get_gametime();
    
    if(fTickAt > fGameTime)
        return;
    
    static iPlayers[32], iPlayer, iNum, i;
    get_players(iPlayers, iNum, "ahi");
    
    if(iNum)
    {
        for(i = 0; i < iNum; i++)
        {
            iPlayer = iPlayers[i];
            
            if((pev_valid(g_iPlayerTrainEnt[iPlayer]) == 2) && (pev_valid(g_iPlayerPlane[iPlayer]) == 2))
            {
                Update_Train(iPlayer, g_iPlayerTrainEnt[iPlayer]);
            }
        }
    }
    
    fTickAt = fGameTime + 0.1;
}

// Function: Update_Train
// Updates the train entity for a player.
//
// Parameters:
//     iID - The player's ID.
//     iEnt - The train entity ID.
//
// Note:
//     This function is called to update the train entity for a player.
//     It checks if the player is still touching the train entity.
//     If not, it resets the train entity and performs additional cleanup.
//     If the player is still touching the train entity, it calculates the new position and updates the train entity accordingly.

Update_Train(const iID, const iEnt)
{
    if(!GetTouchedEntity(iID, g_iPlayerPlane[iID]))
    {
        g_iPlayerPlane[iID] = FM_NULLENT;
        g_iPlayerTrainEnt[iID] = FM_NULLENT;
        g_iPlayerTrainFlags[iID] = FM_NULLENT;
        g_fPlayerOldAngle[iID] = g_fNullAngle;
        
        UnUseTrain(iID);
        
        return;
    }
    
    static Float:fVecPlayerOrigin[3];
    pev(iID, pev_origin, fVecPlayerOrigin);
    
    static Float: fVecPlayerAngles[3];
    pev(iID, pev_angles, fVecPlayerAngles);
    
    static Float: fVecEntOrigin[3];
    pev(iEnt, pev_origin, fVecEntOrigin);
    
    static Float: fAngleDiff, Float: fVecNewOrigin[3];
    fAngleDiff = fVecPlayerAngles[1] - g_fPlayerOldAngle[iID];
    
    if(fAngleDiff < -g_fVecAngleDeg[0])
        fAngleDiff += g_fVecAngleDeg[1];
    
    if(fAngleDiff > g_fVecAngleDeg[0])
        fAngleDiff -= g_fVecAngleDeg[1];
    
    if(fAngleDiff >= g_fAngleDiff)
    {
        fVecPlayerAngles[1] = g_fPlayerOldAngle[iID] + g_fAngleDiff;
        
        if(fVecPlayerAngles[1] > g_fVecAngleDeg[0])
            fVecPlayerAngles[1] -= g_fVecAngleDeg[1];
    }
    else if(fAngleDiff <= -g_fAngleDiff)
    {
        fVecPlayerAngles[1] = g_fPlayerOldAngle[iID] - g_fAngleDiff;
            
        if(fVecPlayerAngles[1] < g_fVecAngleDeg[0])
            fVecPlayerAngles[1] += g_fVecAngleDeg[1];
    }
    
    g_fPlayerOldAngle[iID] = fVecPlayerAngles[1];
    
    if(!(g_iPlayerTrainFlags[iID] & g_iAllowRollFlag))
    {
        fVecPlayerOrigin[2] = fVecEntOrigin[2];
        planar_velocity_by_angle(fVecPlayerOrigin, fVecPlayerAngles, g_fMaxDistance, fVecNewOrigin);
    }
    else
    {
        velocity_by_angle(fVecPlayerOrigin, fVecPlayerAngles, g_fMaxDistance, fVecNewOrigin);
    }
    
    engfunc(EngFunc_SetOrigin, iEnt, fVecNewOrigin);
}

// Function: Handle_TrainMsg
// Handles the Train message received by a player.
//
// Parameters:
//     iMsg - The message ID.
//     iDest - The destination entity ID.
//     iEnt - The player's entity ID.
//
// Returns:
//     PLUGIN_CONTINUE to allow the message to continue processing.
//
// Note:
//     This function is called when a player triggers a Train message.
//     It retrieves the control value from the message and performs actions based on the control value.
//     If the control value is non-zero and the player's train entity is not set, it sets the train entity and performs additional checks.
//     If the control value is zero, it resets the train entity for the player.

public Handle_TrainMsg(const iMsg, const iDest, const iEnt)
{
    new iControl = get_msg_arg_int(1);
    
    if((iControl != 0) && (g_iPlayerTrainEnt[iEnt] == FM_NULLENT))
    {
        new iTrain = pev(iEnt, pev_groundentity);
        
        new szClassName[32];
        pev(iTrain, pev_classname, szClassName, charsmax(szClassName));
    
        if(pev_valid(iTrain) != 2)
        {
            fm_WarningLog("Player #%d triggered Train message with an invalid ground entity id: #%d.", iEnt);
            return PLUGIN_CONTINUE;
        }
        
        g_iPlayerPlane[iEnt] = iTrain;
    
        g_iPlayerTrainFlags[iEnt] = pev(iTrain, pev_skin);
    
        if(!(g_iPlayerTrainFlags[iEnt] & g_iFlyablePlane))
            return PLUGIN_CONTINUE;
    
        new szBuffer[32], iTrainPath = FM_NULLENT;
        pev(iTrain, pev_target, szBuffer, charsmax(szBuffer));
    
        iTrainPath = engfunc(EngFunc_FindEntityByString, iTrainPath, "targetname", szBuffer);
        pev(iTrainPath, pev_target, szBuffer, charsmax(szBuffer));
    
        if(pev_valid(iTrainPath) != 2)
        {
            fm_WarningLog("Path id: #%d of entity id: #%d does not exist.", iTrainPath, iEnt);
            return PLUGIN_CONTINUE;
        }
        
        new Float: fVecPlayerAngles[3];
        pev(iEnt, pev_angles, fVecPlayerAngles);
        
        g_fPlayerOldAngle[iEnt] = fVecPlayerAngles[1];
    
        g_iPlayerTrainEnt[iEnt] = engfunc(EngFunc_FindEntityByString, -1, "targetname", szBuffer);
    }
    else
    {
        if(!iControl)
        {
            g_iPlayerPlane[iEnt] = FM_NULLENT;
            g_iPlayerTrainEnt[iEnt] = FM_NULLENT;
            g_iPlayerTrainFlags[iEnt] = FM_NULLENT;
            g_fPlayerOldAngle[iEnt] = g_fNullAngle;
        }
    }
    
    return PLUGIN_CONTINUE;
}

// Function: GetPlayerEntity
// Retrieves the entity that the player is currently interacting with.
//
// Parameters:
//     iID - The player's entity ID.
//     fDistance - The maximum distance to check for entities (default: g_fMaxDistance).
//
// Returns:
//     The entity ID of the player's interaction target, or -1 if no entity is found.
//
// Note:
//     This function uses a trace line to determine the entity that the player is interacting with.
//     It takes into account the player's position, view offset, and angles to perform the trace.
//     The fDistance parameter specifies the maximum distance to check for entities.
//     If an entity is found within the specified distance, its entity ID is returned.
//     If no entity is found, -1 is returned.

GetPlayerEntity(const iID, const Float: fDistance = g_fMaxDistance)
{
    static Float: fVecOrigin[3], Float: fVecAngles[3], Float: fVecDown[3], Float: fVecEnd[3];

    pev(iID, pev_origin, fVecOrigin);
    pev(iID, pev_view_ofs, fVecDown);

    xs_vec_add(fVecOrigin, fVecDown, fVecOrigin);

    pev(iID, pev_angles, fVecAngles);

    angle_vector(fVecAngles, ANGLEVECTOR_UP, fVecDown);
    xs_vec_neg(fVecDown, fVecDown);
    
    xs_vec_add_scaled(fVecOrigin, fVecDown, fDistance, fVecEnd);
    
    static iTrace, iHit, Float: fFraction;
    iTrace = create_tr2();

    engfunc(EngFunc_TraceLine, fVecOrigin, fVecEnd, IGNORE_MONSTERS, iID, iTrace);
    
    iHit = get_tr2(iTrace, TR_pHit);
    get_tr2(iTrace, TR_flFraction, fFraction);

    free_tr2(iTrace);

    if(fFraction >= 1.0)
        return -1;

    return (pev_valid(iHit) == 2) ? iHit : 0;
}

// Function: GetTouchedEntity
// Retrieves the entity that the player is currently touching or within a certain distance from.
//
// Parameters:
//     iID - The player's entity ID.
//     iPlane - The entity ID of the plane to check for touch.
//
// Returns:
//     The entity ID of the touched entity or the entity within the specified distance, or 0 if no entity is found.
//
// Note:
//     This function checks if the player is touching the specified plane entity or if there is any entity within a certain distance from the player's position.
//     It uses the GetPlayerEntity function to determine the player's interaction target.
//     If the player is touching the specified plane entity or if there is any entity within the specified distance, its entity ID is returned.
//     If no entity is found, 0 is returned.

UnUseTrain(const iID)
{
    static iFlags;
    iFlags = pev(iID, pev_flags);
    
    if(iFlags & FL_ONTRAIN)
        set_pev(iID, pev_flags, iFlags & ~FL_ONTRAIN);
    
    static iButtons;
    pev(iID, pev_button, iButtons);
    
    if(iButtons & IN_USE)
    {
        set_pev(iID, pev_button, iButtons & ~IN_USE);
        set_pev(iID, pev_oldbuttons, pev(iID, pev_oldbuttons) | IN_USE); 
    }
    
    static iPhysFlags;
    iPhysFlags = get_ent_data(iID, "CBasePlayer", "m_afPhysicsFlags");
    
    if(iPhysFlags &= PFLAG_ONTRAIN)
    {
        iPhysFlags &= ~PFLAG_ONTRAIN;
        set_ent_data(iID, "CBasePlayer", "m_afPhysicsFlags", iPhysFlags);
    }
    
    message_begin(MSG_ONE, g_iMsgTrain, _, iID);
    write_byte(0);
    message_end();
}

// Function: velocity_by_angle
// Calculates the velocity vector based on the origin, angles, and distance.
//
// Parameters:
//     fVecOrigin - The origin vector.
//     fVecAngles - The angles vector.
//     fDistance - The distance value.
//     fVecOutput - The output vector to store the calculated velocity.
//
// Note:
//     This function calculates the velocity vector based on the origin, angles, and distance.
//     It uses trigonometric functions to calculate the x, y, and z components of the velocity vector.
//     The calculated velocity vector is stored in the fVecOutput parameter.

velocity_by_angle(const Float: fVecOrigin[3], Float: fVecAngles[3], const Float: fDistance, Float: fVecOutput[3])
{
    fVecAngles[0] *= g_fAngleMultiplier;
    
    fVecOutput[0] = fVecOrigin[0] + fDistance * floatcos(fVecAngles[1], degrees);
    fVecOutput[1] = fVecOrigin[1] + fDistance * floatsin(fVecAngles[1], degrees);
    fVecOutput[2] = fVecOrigin[2] + fDistance * floatsin(fVecAngles[0], degrees);
}

// Function: planar_velocity_by_angle
// Calculates the planar velocity vector based on the origin, angles, and distance.
//
// Parameters:
//     fVecOrigin - The origin vector.
//     fVecAngles - The angles vector.
//     fDistance - The distance value.
//     fVecOutput - The output vector to store the calculated planar velocity.
//
// Note:
//     This function calculates the planar velocity vector based on the origin, angles, and distance.
//     It uses trigonometric functions to calculate the x and y components of the velocity vector.
//     The z component of the velocity vector is set to the origin's z component.
//     The calculated planar velocity vector is stored in the fVecOutput parameter.

planar_velocity_by_angle(const Float: fVecOrigin[3], Float: fVecAngles[3], const Float: fDistance, Float: fVecOutput[3])
{
    fVecAngles[0] *= g_fAngleMultiplier;
    
    fVecOutput[0] = fVecOrigin[0] + fDistance * floatcos(fVecAngles[1], degrees);
    fVecOutput[1] = fVecOrigin[1] + fDistance * floatsin(fVecAngles[1], degrees);
    fVecOutput[2] = fVecOrigin[2];
}`

**Comment by MrCoala** [comment]
[FM_DRIVE_mk.txt](https://github.com/TFC-Developers/fm_base_plugins/files/13789386/FM_DRIVE_mk.txt)
Can you check my changes please and update your repository? I added comments. You need to make sure the changes are not breaking anything

**Comment by DarthMan** [comment]
> [FM_DRIVE_mk.txt](https://github.com/TFC-Developers/fm_base_plugins/files/13789386/FM_DRIVE_mk.txt) Can you check my changes please and update your repository? I added comments. You need to make sure the changes are not breaking anything

Sure, will do that now.

**Comment by VANCOLD** [comment]
Do me a favor: if you change stuff summarize it, i have to read the code anyway but it is nice for anyone who didn't review or work on the code to understand the thought process <3

**Comment by DarthMan** [comment]
This plugin is an improvement over the original SYC plugin for various reasons. Among them, I'll enumerate the important ones

1. It uses server frame to update the train entities for the players controlling them, rather than creating an entity and making it constantly think, thus reducing the amount of entities on the server.
2. If the player is no longer touching the train, it automatically gets de-activated and returns to the spawn origin. The train icon hud is also removed from the player.
3. It also checks if the train entities are valid with pvPrivateData, and if not, warnings are thrown.
4. It uses the FM api, unlike the original plugin which makes use of the standard AMXX natives.

**Comment by VANCOLD** [comment]
I've tested the script and this is my feedback:
- trains that are moved but turned off dont reset
- the trains angels dont get properly reset after arriving

**Comment by VANCOLD** [comment]
after talking to darthman again this is intended behaviour, the velocity needs to be present to reset for reseting the vehicle so this should be fine

**Review by VANCOLD — APPROVED** [review]

**Pull request merged**
